#!/usr/bin/env python3

import argparse
import os
import shlex
import shutil
import subprocess
from pathlib import Path


def read_dataset(path):
    return [
        x.strip()
        for x in Path(path).read_text().splitlines()
        if x.strip() and not x.strip().startswith("#")
    ]


def chunks(items, size):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def is_eos_path(path):
    try:
        resolved = Path(path).expanduser().resolve()
    except Exception:
        resolved = Path(path).expanduser().absolute()

    return str(resolved).startswith("/eos/")


def eos_to_xrootd(path):
    path = str(path)
    if path.startswith("/eos/"):
        return "root://eosuser.cern.ch/" + path
    return path


def choose_work_dir(tag, requested_work_dir=None):
    if requested_work_dir:
        return Path(requested_work_dir).expanduser().resolve() / tag

    repo_work_dir = Path("condor") / "work" / tag

    # If repository is not on EOS, local repo workdir is fine.
    if not is_eos_path(Path.cwd()):
        return repo_work_dir.resolve()

    # If repository is on EOS, avoid putting Condor submit/log files there.
    home = Path.home()
    if not is_eos_path(home):
        return (home / "condor_work" / "Reco2Pico" / tag).resolve()

    # Last fallback.
    user = os.environ.get("USER", "user")
    return Path(f"/tmp/{user}/condor_work/Reco2Pico/{tag}").resolve()


def assert_no_eos_in_submit_file(sub_text):
    bad_lines = []

    for idx, line in enumerate(sub_text.splitlines(), start=1):
        clean = line.split("#", 1)[0].strip()
        lower = clean.lower()

        if "/eos/" in clean:
            bad_lines.append(f"{idx}: contains /eos/: {line}")

        if "$(env(" in lower:
            bad_lines.append(f"{idx}: contains $(ENV(...)): {line}")

        if lower.startswith("getenv"):
            value = lower.split("=", 1)[1].strip() if "=" in lower else ""
            if value not in ("false", "0", ""):
                bad_lines.append(f"{idx}: unsafe getenv setting: {line}")

    if bad_lines:
        raise SystemExit(
            "ERROR: generated Condor submit file is not safe for standard CERN schedds.\n\n"
            + "\n".join(bad_lines)
        )


def write_generated_wrapper(wrapper_path, implementation_path, output_dir):
    """
    Generate the actual Condor executable.

    The output directory may be:
        root://eosuser.cern.ch//eos/...

    That value is embedded here in the shell script, not in pico.sub.
    Therefore the submit file remains free of /eos/.
    """

    output_dir = eos_to_xrootd(output_dir).rstrip("/")

    wrapper_text = f"""#!/bin/bash
set -euo pipefail

# Generated by submit_pico.py.
# Do not edit by hand.

if [ "$#" -ne 6 ]; then
    echo "ERROR: expected 6 arguments, got $#"
    echo "Usage: $0 PROC_ID JOB_LIST CFG TABLES GLOBAL_TAG MAX_EVENTS"
    exit 1
fi

PROC_ID="$1"
JOB_LIST="$2"
CFG="$3"
TABLES="$4"
GLOBAL_TAG="$5"
MAX_EVENTS="$6"

# The real output directory is intentionally embedded here,
# not in the Condor submit file.
OUTPUT_DIR={shlex.quote(output_dir)}

IMPLEMENTATION={shlex.quote(str(implementation_path))}

exec "$IMPLEMENTATION" \\
    "$PROC_ID" \\
    "$JOB_LIST" \\
    "$CFG" \\
    "$OUTPUT_DIR" \\
    "$TABLES" \\
    "$GLOBAL_TAG" \\
    "$MAX_EVENTS"
"""

    wrapper_path.write_text(wrapper_text)
    wrapper_path.chmod(0o755)


def write_submit_file(
    sub_path,
    wrapper_path,
    job_list_path,
    cfg,
    tables,
    global_tag,
    max_events,
    logs_dir,
    n_jobs,
):
    """
    Write a submit file that contains no /eos/ paths and does not import
    the submitter environment.
    """

    sub_text = f"""universe = vanilla

executable = {wrapper_path}
arguments  = $(ProcId) {job_list_path} {cfg} {tables} {global_tag} {max_events}

log    = {logs_dir}/pico.$(ClusterId).log
output = {logs_dir}/pico.$(ClusterId).$(ProcId).out
error  = {logs_dir}/pico.$(ClusterId).$(ProcId).err

getenv = False

should_transfer_files = NO

queue {n_jobs}
"""

    assert_no_eos_in_submit_file(sub_text)
    sub_path.write_text(sub_text)


def clean_condor_submit_env():
    """
    Avoid passing EOS-based environment variables to condor_submit.

    The important part is that pico.sub has getenv=False, but this also
    avoids accidental expansion or submit-side checks seeing EOS paths
    through PWD, CMSSW_BASE, PYTHONPATH, etc.
    """

    keep = [
        "HOME",
        "USER",
        "LOGNAME",
        "SHELL",
        "LANG",
        "LC_ALL",
        "X509_USER_PROXY",
        "BEARER_TOKEN_FILE",
        "KRB5CCNAME",
    ]

    env = {}

    for key in keep:
        value = os.environ.get(key)
        if value and "/eos/" not in value:
            env[key] = value

    # Keep a sanitized PATH.
    path = os.environ.get("PATH", "")
    if path:
        clean_parts = [p for p in path.split(":") if p and "/eos/" not in p]
        if clean_parts:
            env["PATH"] = ":".join(clean_parts)

    return env


def main():
    parser = argparse.ArgumentParser(description="Submit Reco2Pico production jobs to Condor")

    parser.add_argument("--dataset", required=True)
    parser.add_argument("--cfg", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--files-per-job", type=int, default=1)
    parser.add_argument("--tables", default="event,muons,electrons,jets,met,custom_objects")
    parser.add_argument("--global-tag", default="auto:phase1_2024_realistic")
    parser.add_argument("--max-events", default="-1")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--work-dir",
        default=None,
        help=(
            "Base directory for Condor submit files/logs. "
            "If not set, a safe non-EOS directory is chosen automatically."
        ),
    )

    args = parser.parse_args()

    if str(args.cfg).startswith("/eos/"):
        raise SystemExit(
            "ERROR: --cfg cannot be a raw /eos path for standard Condor schedds. "
            "Use a relative path, e.g. "
            "PicoProducer/python/workflows/miniAOD_to_pico_cfg.py"
        )

    files = read_dataset(args.dataset)
    if not files:
        raise SystemExit(f"No input files found in {args.dataset}")

    repo_dir = Path(__file__).resolve().parents[1]
    template_job = repo_dir / "condor" / "templates" / "pico_job.sh"

    if not template_job.exists():
        raise SystemExit(f"ERROR: missing job template: {template_job}")

    work_dir = choose_work_dir(args.tag, args.work_dir)
    lists_dir = work_dir / "input_lists"
    logs_dir = work_dir / "logs"

    work_dir.mkdir(parents=True, exist_ok=True)
    lists_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    print(f"Using Condor work directory: {work_dir}")

    job_inputs = []
    for idx, group in enumerate(chunks(files, args.files_per_job)):
        input_list = lists_dir / f"input_{idx:05d}.txt"
        input_list.write_text("\n".join(group) + "\n")
        job_inputs.append(input_list)

    job_list_path = work_dir / "job_inputs.txt"
    job_list_path.write_text("\n".join(str(p) for p in job_inputs) + "\n")

    # Copy original implementation script to the safe Condor work directory.
    implementation_path = work_dir / "pico_job_impl.sh"
    shutil.copy2(template_job, implementation_path)
    implementation_path.chmod(0o755)

    # Generate the actual Condor executable.
    wrapper_path = work_dir / "pico_job.sh"
    write_generated_wrapper(
        wrapper_path=wrapper_path,
        implementation_path=implementation_path,
        output_dir=args.output_dir,
    )

    # Generate pico.sub directly, avoiding stale/unsafe template settings.
    sub_path = work_dir / "pico.sub"
    write_submit_file(
        sub_path=sub_path,
        wrapper_path=wrapper_path,
        job_list_path=job_list_path,
        cfg=args.cfg,
        tables=args.tables,
        global_tag=args.global_tag,
        max_events=str(args.max_events),
        logs_dir=logs_dir,
        n_jobs=len(job_inputs),
    )

    print(f"Prepared {len(job_inputs)} jobs")
    print(f"Submit file: {sub_path}")
    print(f"Generated wrapper: {wrapper_path}")
    print(f"Copied implementation: {implementation_path}")

    # Helpful diagnostics.
    print()
    #print("Checking generated submit file for forbidden EOS paths:")
    subprocess.run(["grep", "-nE", r"/eos|ENV|getenv|initialdir|environment", str(sub_path)], check=False)

    if args.dry_run:
        print()
        print("Dry run only; not submitting.")
        return

    condor_submit = shutil.which("condor_submit") or "condor_submit"

    subprocess.run(
        [condor_submit, str(sub_path)],
        check=True,
        cwd=str(work_dir),
        env=clean_condor_submit_env(),
    )


if __name__ == "__main__":
    main()